version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    
    #image: pythontest
    #Building image from Dockerfile not prebuilt image
    build: .
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
    networks:
      - webnet
networks:
  webnet: