version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    
    #image: pythontest
    #Building image from Dockerfile not prebuilt image
    build: .
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5501:5000"
    networks:
      - webnet
    depends_on:
      - mysql
    links:
      - mysql:mysql
    environment: 
      INV_SECRET_KEY: ${INV_SECRET_KEY}
      INV_DB_USERNAME: ${INV_DB_USERNAME}
      INV_DB_PASS: ${INV_DB_PASS}
      INV_JWT_USER: ${INV_JWT_USER}
      INV_JWT_PASS: ${INV_JWT_PASS}

  #builds and starts mysql image from database folder
  mysql:  
    build: 
      context: ./src/database
      dockerfile: dockerfile
    container_name: mysql
  # Sets up variables 
    environment:
      MYSQL_ROOT_PASSWORD: ${INV_ROOT_PASS}
      MYSQL_DATABASE: inventory
      MYSQL_USER: ${INV_DB_USERNAME}
      MYSQL_PASSWORD: ${INV_DB_PASS}
    ports: 
      - "3501:3306"
networks:
  webnet:
