-- MySQL Script generated by MySQL Workbench
-- Tue Oct 23 16:03:43 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema logistics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema logistics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `logistics` DEFAULT CHARACTER SET utf8 ;
USE `logistics` ;

-- -----------------------------------------------------
-- Table `logistics`.`locations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics`.`locations` (
  `idlocations` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idlocations`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `logistics`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `logistics`.`inventory` (
  `idinventory` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `amount` INT NULL,
  `locationID` INT NULL,
  PRIMARY KEY (`idinventory`),
  INDEX `fk_inventory_locations_idx` (`locationID` ASC) VISIBLE,
  CONSTRAINT `fk_inventory_locations`
    FOREIGN KEY (`locationID`)
    REFERENCES `logistics`.`locations` (`idlocations`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
